[copyq-darwin]
src.github = "hluk/CopyQ"
src.prefix = "v"
fetch.url = "https://github.com/hluk/CopyQ/releases/download/v$ver/CopyQ.dmg.zip"

[nixfmt]
src.git = "https://github.com/piegamesde/nixfmt"
src.branch = "rfc101-style"
fetch.github = "piegamesde/nixfmt"

[nixpkgs-review]
src.git = "https://github.com/natsukium/nixpkgs-review"
src.branch = "r-rmcgibbo-1"
fetch.github = "natsukium/nixpkgs-review"

[nowplaying-cli]
src.github = "kirtan-shah/nowplaying-cli"
src.prefix = "v"
fetch.url = "https://github.com/kirtan-shah/nowplaying-cli/archive/v$ver.tar.gz"

[qmk-toolbox]
src.github = "qmk/qmk_toolbox"
fetch.url = "https://github.com/qmk/qmk_toolbox/releases/download/$ver/QMK.Toolbox.app.zip"

[qutebrowser-darwin]
src.github = "qutebrowser/qutebrowser"
src.prefix = "v"
fetch.url = "https://github.com/qutebrowser/qutebrowser/releases/download/v$ver/qutebrowser-$ver.dmg"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
src.branch = "main"
fetch.github = "vim-skk/skkeleton"

[vivaldi-darwin]
src.archpkg = "vivaldi"
fetch.url = "https://downloads.vivaldi.com/stable/Vivaldi.$ver.universal.dmg"
