# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  claudecode-nvim = {
    pname = "claudecode-nvim";
    version = "432121f0f5b9bda041030d1e9e83b7ba3a93dd8f";
    src = fetchFromGitHub {
      owner = "coder";
      repo = "claudecode.nvim";
      rev = "432121f0f5b9bda041030d1e9e83b7ba3a93dd8f";
      fetchSubmodules = false;
      sha256 = "sha256-r8hAUpSsr8zNm+av8Mu5oILaTfEsXEnJmkzRmvi9pF8=";
    };
    date = "2026-03-04";
  };
  copyq-darwin = {
    pname = "copyq-darwin";
    version = "13.0.0";
    src = fetchurl {
      url = "https://github.com/hluk/CopyQ/releases/download/v13.0.0/CopyQ-macos-12-m1.dmg.zip";
      sha256 = "sha256-LrdDzFepf95scdbsBYdAiuK+tBk5aZEX0yt05oiC534=";
    };
  };
  emacs-plus = {
    pname = "emacs-plus";
    version = "707e967a0edd465f99ec82d5129c873e6a89ba73";
    src = fetchFromGitHub {
      owner = "d12frosted";
      repo = "homebrew-emacs-plus";
      rev = "707e967a0edd465f99ec82d5129c873e6a89ba73";
      fetchSubmodules = false;
      sha256 = "sha256-qqtivPF8QZ90pyXG2tx/bY5orbp8Xnb+6LuVakyKVnA=";
    };
    date = "2026-03-14";
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.1.1/Hammerspoon-1.1.1.zip";
      sha256 = "sha256-EbsckPr1Qn83x71P5+q5d0rkPh1csCDFswiNrDKEnvo=";
    };
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "5c3f35b870daa036fc03acc3dfe694ff7ea29963";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "5c3f35b870daa036fc03acc3dfe694ff7ea29963";
      fetchSubmodules = false;
      sha256 = "sha256-mD+1HDw+20oDO/7iJtSZ8TgEL3DP56lYDX/DAXXbefU=";
    };
    date = "2026-03-12";
  };
  qmk-toolbox = {
    pname = "qmk-toolbox";
    version = "0.3.3";
    src = fetchurl {
      url = "https://github.com/qmk/qmk_toolbox/releases/download/0.3.3/QMK.Toolbox.app.zip";
      sha256 = "sha256-WPre2csGAQzavtksLbj3L/MrWUT6d2gTJVq7eAmpcLk=";
    };
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.6.3";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.6.3/qutebrowser-3.6.3-arm64.dmg";
      sha256 = "sha256-Kk+uWs2QJouaD9U5ma3AJsR4HtqW/Blh8zM9Faj1u00=";
    };
  };
  sbarlua = {
    pname = "sbarlua";
    version = "dba9cc421b868c918d5c23c408544a28aadf2f2f";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "dba9cc421b868c918d5c23c408544a28aadf2f2f";
      fetchSubmodules = false;
      sha256 = "sha256-lhLTrdufA3ALJ2S5HLdgNOr5seWIWEHkVhZNPObzbvI=";
    };
    date = "2026-03-06";
  };
  skills-ref = {
    pname = "skills-ref";
    version = "36a4d328c047e1d331fa173cc46f193429ca7897";
    src = fetchFromGitHub {
      owner = "agentskills";
      repo = "agentskills";
      rev = "36a4d328c047e1d331fa173cc46f193429ca7897";
      fetchSubmodules = false;
      sha256 = "sha256-Wi8+m2eO4AcgbwsIbeEmAGho50khApRghpO5df1JlnA=";
    };
    date = "2026-03-13";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "158ae753bc5099ab12537c23152926c42b1f7c3a";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "158ae753bc5099ab12537c23152926c42b1f7c3a";
      fetchSubmodules = false;
      sha256 = "sha256-Ee55oGlNCoKwvDxaJyRCjqY89+DU2bP+7t8o/kkh8lU=";
    };
    date = "2026-01-04";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "7.8.3925.81";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.7.8.3925.81.universal.dmg";
      sha256 = "sha256-z6dtywlVwHYBJgtwiFkqszGfyMurf0HiJ8R1pqVlKZM=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.19.2b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.19.2b/zen.macos-universal.dmg";
      sha256 = "sha256-m595vem8Sjgls3tiIr8AIYTbQtkPS6OMqY0+gkeJxgo=";
    };
  };
}
