# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  claudecode-nvim = {
    pname = "claudecode-nvim";
    version = "432121f0f5b9bda041030d1e9e83b7ba3a93dd8f";
    src = fetchFromGitHub {
      owner = "coder";
      repo = "claudecode.nvim";
      rev = "432121f0f5b9bda041030d1e9e83b7ba3a93dd8f";
      fetchSubmodules = false;
      sha256 = "sha256-r8hAUpSsr8zNm+av8Mu5oILaTfEsXEnJmkzRmvi9pF8=";
    };
    date = "2026-03-04";
  };
  copyq-darwin = {
    pname = "copyq-darwin";
    version = "13.0.0";
    src = fetchurl {
      url = "https://github.com/hluk/CopyQ/releases/download/v13.0.0/CopyQ-macos-12-m1.dmg.zip";
      sha256 = "sha256-LrdDzFepf95scdbsBYdAiuK+tBk5aZEX0yt05oiC534=";
    };
  };
  emacs-plus = {
    pname = "emacs-plus";
    version = "0dedfe306b373766f0a0401b7ba8e3a5623886dc";
    src = fetchFromGitHub {
      owner = "d12frosted";
      repo = "homebrew-emacs-plus";
      rev = "0dedfe306b373766f0a0401b7ba8e3a5623886dc";
      fetchSubmodules = false;
      sha256 = "sha256-uUnTPl+finoOYPKlpM+HQS+LamntgaQ0vaH7IY2yFek=";
    };
    date = "2026-03-07";
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.1.1/Hammerspoon-1.1.1.zip";
      sha256 = "sha256-EbsckPr1Qn83x71P5+q5d0rkPh1csCDFswiNrDKEnvo=";
    };
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "f86f76bae635307d6cb12c8d66693acff57cf82a";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "f86f76bae635307d6cb12c8d66693acff57cf82a";
      fetchSubmodules = false;
      sha256 = "sha256-+mmvWshi619WqZFmmkua9gE28PWhpspUV/J2vNmKtKM=";
    };
    date = "2026-03-07";
  };
  qmk-toolbox = {
    pname = "qmk-toolbox";
    version = "0.3.3";
    src = fetchurl {
      url = "https://github.com/qmk/qmk_toolbox/releases/download/0.3.3/QMK.Toolbox.app.zip";
      sha256 = "sha256-WPre2csGAQzavtksLbj3L/MrWUT6d2gTJVq7eAmpcLk=";
    };
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.6.3";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.6.3/qutebrowser-3.6.3-arm64.dmg";
      sha256 = "sha256-Kk+uWs2QJouaD9U5ma3AJsR4HtqW/Blh8zM9Faj1u00=";
    };
  };
  sbarlua = {
    pname = "sbarlua";
    version = "dba9cc421b868c918d5c23c408544a28aadf2f2f";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "SbarLua";
      rev = "dba9cc421b868c918d5c23c408544a28aadf2f2f";
      fetchSubmodules = false;
      sha256 = "sha256-lhLTrdufA3ALJ2S5HLdgNOr5seWIWEHkVhZNPObzbvI=";
    };
    date = "2026-03-06";
  };
  skills-ref = {
    pname = "skills-ref";
    version = "a3d02daa99ff01467e3bec94b038933416b7d8d8";
    src = fetchFromGitHub {
      owner = "agentskills";
      repo = "agentskills";
      rev = "a3d02daa99ff01467e3bec94b038933416b7d8d8";
      fetchSubmodules = false;
      sha256 = "sha256-U5uizh1jcESVvmRHZL1vKWcoRwJjCwT23WQbP+Lo4zQ=";
    };
    date = "2026-03-05";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "158ae753bc5099ab12537c23152926c42b1f7c3a";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "158ae753bc5099ab12537c23152926c42b1f7c3a";
      fetchSubmodules = false;
      sha256 = "sha256-Ee55oGlNCoKwvDxaJyRCjqY89+DU2bP+7t8o/kkh8lU=";
    };
    date = "2026-01-04";
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "7.8.3925.76";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.7.8.3925.76.universal.dmg";
      sha256 = "sha256-SP+FEpfWE8lPsHu7NNAwhXYBgnqJ4dXa0z20rob+QYA=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.19.1b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.19.1b/zen.macos-universal.dmg";
      sha256 = "sha256-BLPN2LA57nsk4vm8NnnBYwHbJh6L4LMU78Vb2adE5sg=";
    };
  };
}
