name: "Update source and create PR"
on:
  schedule:
    - cron:  '0 19 * * *'
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Update sources
      run: nix run nixpkgs#nvfetcher
    - name: Update readme
      run: |
        nix run nixpkgs#emacs -- -l ob -l ob-shell --batch --eval "
          (progn
            (let ((org-confirm-babel-evaluate nil))
            (dolist (file command-line-args-left)
              (with-current-buffer (find-file-noselect file)
                (org-babel-execute-buffer)
                (save-buffer)))))
          " README.org
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PAT }}
        committer: actions-user <action@github.com>
        author: actions-user <action@github.com>
        commit-message: "update source"
        title: "update source"
