name: "Update flake and create PR"
on:
  schedule:
    - cron:  '0 19 * * 6'
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Update flake inputs
      run: nix flake update
    - name: Update readme
      run: nix develop -c update-readme
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PAT }}
        committer: actions-user <action@github.com>
        author: actions-user <action@github.com>
        commit-message: "chore(deps): update flake inputs"
        title: "chore(deps): update flake inputs"
