name: "Update source and create PR"
on:
  schedule:
    - cron:  '0 19 * * *'
  workflow_dispatch:
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Update sources
      run: nix run nixpkgs#nvfetcher
    - name: Update readme
      run: nix develop -c update-readme
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ steps.app-token.outputs.token }}
        commit-message: "update source"
        title: "update source"
        branch: update-nvfetcher
        sign-commits: true
    - name: Enable auto-merge
      if: steps.cpr.outputs.pull-request-number
      run: |
        gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
